version: '3.9'

services:
  app:
    build:
      context: .
    container_name: xbarber-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    container_name: xbarber-db
    environment:
      POSTGRES_USER: mtsouk
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: restapi
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local

# Путь к стандартной папке для хранения всех файлов базы данных Postgres
# - ./.database/postgres/data:/var/lib/postgresql/data 
