# Server configurations
http_server:
  port: 8080
  timeout: 5s
  write_timeout: 5s
  idle_timeout: 10s

# Database credentials
database:
  host: "localhost"
  port: "5432"
  user: "username"
  password: "password"
  dbname: "database_name"