# Server configurations
http_server:
  port: 8080
  timeout: 5s
  write_timeout: 5s
  idle_timeout: 10s

# Database credentials
db:
  dbname: "postgres"
  host: "db" # db - это имя сервиса в docker-compose.yaml
  port: "5432"
  user: "postgres"