name: Deploy to Docker Hub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Publish Docker Image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: barber_schedule
        run: |
          docker images

          docker buildx create --name multi-arch-builder --use --bootstrap

          docker buildx build --platform linux/amd64,linux/arm64 .

          docker buildx inspect multi-arch-builder
          docker buildx ls

          echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin

          docker buildx build --push \
                              --platform linux/arm64,linux/amd64 \
                              --tag "$USERNAME/${IMAGE_NAME}:latest" \
                              .
